package szczepan;
import java.util.Map.Entry;
import java.util.HashMap;
import java.util.Arrays;
import java.util.List;

public class SkladnikiMap {
    public static HashMap<String, List<String>> getSkladnikiMap() {
        HashMap<String, List<String>> skladniki = new HashMap<>();
        skladniki.put("krewetka", Arrays.asList("krewetek", "krewetki" , "krewetka" ));
        skladniki.put("kraby", Arrays.asList("kraby", "krabów"));
        skladniki.put("majonez", Arrays.asList("majonez","majonezu", "dobry majonez", "dobrego majonezu", "gęstego majonezu"));
        skladniki.put("koniak", Arrays.asList("koniak", "koniaku"));
        skladniki.put("brandy", Arrays.asList("brandy"));
        skladniki.put("pomarańcza", Arrays.asList("pomarańcza", "pomarańcze", "sok z pomarańczy", "soku z pomarańczy", "otarta skórka z pomarańczy", "skórka z pomarańczy", "soku pomarańczowego", "duża bezpestkowa pomarańcza", "startej skórki pomarańczowej"));
        skladniki.put("pomidor", Arrays.asList("pomidor", "pomidory", "przecier pomidorowy", "przecieru pomidorowego", "dojrzałe, jędrne pomidory", "dojrzałych, jędrnych pomidorów", "pomidorów", "sok pomidorowy", "soku pomidorowego", "koncentrat pomidorowy", "koncentratu pomidorowego", "dużych pomidorów", "dojrzały pomidor", "suszone pomidory", "suszonych pomidorów", "dojrzałe pomidory ewentualnie pomidory z puszki lub przecier pomidorowy", "puszki pomidorów bez skóry", "pomidorów bez skóry", "pomidorków"));
        skladniki.put("cytryna", Arrays.asList("cytryna", "cytryny", "mała cytryna", "małej cytryny", "sok z cytryny", "sok z małej cytryny", "soku z cytryny", "sok cytrynowy", "sok cytrynowy do smaku", "kwasek cytrynowy", "kwasek cytrynowy do smaku", "sok z jednej cytryny", "sok z połówki cytryny", "startej skórki cytrynowej" ));
        skladniki.put("cebula", Arrays.asList("cebula", "cebule", "nieduże cebule", "cebulki", "cebulek", "małych cebulek", "cebuli", "dymki", "szalotki", "pokrojone w plasterki dymki", "średniej wielkości cebule", "duża cebula", "mała cebula", "czerwona cebula", "dymki ze szczypiorkiem", "cebula dymka", "cebulka dymka"));
        skladniki.put("tatar", Arrays.asList("tatar", "mięso na tatar", "mięsa na tatar"));
        skladniki.put("kapary", Arrays.asList("kapary", "kaparów"));
        skladniki.put("papryka", Arrays.asList("papryka", "papryki", "papryczki","czerwona papryka", "czerwonej papryki", "pokrojona papryka", "ostra papryka", "mielona ostra papryka", "dojrzałe czerwone papryki", "zielona papryka", "słodkiej papryki w proszku", "słodkiej papryki", "słodkiej mielonej papryki", "żółta papryka", "żółtej papryki", "zielonej papryki", "ostrej papryki", "papryka w proszku", "czerwonej słodkiej papryki", "ostra papryka w proszku", "słodka papryka w proszku", "ostra, marynowana papryka", "mielona papryka", "papryka czerwona", "papryki mielonej"));
        skladniki.put("pesto", Arrays.asList("pesto", "sos pesto", "sosu pesto"));
        skladniki.put("szynka", Arrays.asList("szynka", "szynki", "szynki pokrojonej w cienkie plastry", "szynka pokrojona w cienkie plastry"));
        skladniki.put("oliwa", Arrays.asList("oliwa", "oliwy", "oliwa z oliwek", "oliwy z oliwek", "oliwa do smażenia"));
        skladniki.put("ser pleśniowy", Arrays.asList("ser pleśniowy", "sera pleśniowego", "rokpol", "rokpola", "sera pleśniowego, najlepiej rokpola"));
        skladniki.put("ser żółty", Arrays.asList("ser żółty", "żólty ser", "żółtego, pikantnego sera", "startego sera żółtego", "żółtego sera", "startego żółtego sera", "startego żółtego sera (najlepiej parmezanu)", "tartego parmezanu", "parmezanu", "parmezan"));
        skladniki.put("pieczarki", Arrays.asList("pieczarki", "pieczarek", "marynowane pieczarki", "marynowanych pieczarek"));
        skladniki.put("oliwki", Arrays.asList("oliwki", "oliwek", "marynowane zielone oliwki z papryką", "marynowanych zielonych oliwek z papryką", "czarnych oliwek"));
        skladniki.put("pietruszka", Arrays.asList("pietruszka", "pietruszki", "natka pietruszki", "posiekana natka pietruszki", "gałązka pietruszki", "gałązki pietruszki", "natki pietruszki", "młoda pietruszka", "młodej pietruszki", "siekanej natki pietruszki", "mała pietruszka", "zielonej pietruszki", "korzenia pietruszki"));
        skladniki.put("sól", Arrays.asList("sól", "soli", "sól morska"));
        skladniki.put("groszek", Arrays.asList("groszek", "groszku","zielony groszek", "zielonego groszku", "zielonego groszku konserwowanego", "groszek ptysiowy", "groszku konserwowego", "świeżego groszku"));
        skladniki.put("sałata", Arrays.asList("sałata", "sałaty", "średniej długości liści sałaty", "listki sałaty", "zielonej sałaty"));
        skladniki.put("jaja", Arrays.asList("jaja", "jajka", "jajek", "jajka ugotowane na twardo", "jajek ugotowanych na twardo", "jajko surowe", "żółtko", "żółtka", "jajo", "jajko", "białko", "białka"));
        skladniki.put("kukurydza", Arrays.asList("kukurydza", "kukurydzy", "kukurydzy z puszki", "duże puszki kukurydzy"));
        skladniki.put("śmietana", Arrays.asList("śmietana", "śmietany", "gęstej śmietany", "kwaśnej śmietany", "gęstej kwaśnej śmietany", "kwaśnej gęstej śmietany", "śmietanka", "słodka śmietanka", "śmietany 22%", "śmietany 12%", "śmietanki", "śmietany 36%", "śmietanki 36%", "śmietana kremówka", "słodka śmietana kremówka", "śmietany kremówki", "słodkiej śmietany kremówki", "świeżej śmietany", "gęstej, kwaśnej śmietany", "słodkiej śmietany", "kwaśnej śmietany kremowej", "słodkiej śmietany kremowej"));
        skladniki.put("rzodkiewka", Arrays.asList("rzodkiewka", "rzodkiewki", "rzodkiewek", "białej rzodkiew", "duże pęczki rzodkiewki", "utartych rzodkiewek"));
        skladniki.put("szczypiorek", Arrays.asList("szczypiorek", "szczypiorku", "posiekanego szczypiorku", "siekanego szczypiorku", "dymki ze szczypiorkiem"));
        skladniki.put("musztarda", Arrays.asList("musztarda", "musztardy", "musztardy delikatesowej", "musztardy dijon", "ostrej musztardy"));
        skladniki.put("masło", Arrays.asList("masło", "masła", "masła roślinnego"));
        skladniki.put("mleko", Arrays.asList("mleko", "mleka", "zsiadłe mleko", "zsiadłego mleka", "mleko kokosowe", "mleka kokosowego"));
        skladniki.put("parówki", Arrays.asList("parówki", "parówek"));
        skladniki.put("boczek", Arrays.asList("boczek", "boczku", "cienkich plastrów wędzonego boczku", "wędzonego boczku", "chudego wędzonego boczku", "boczku wędzonego", "surowego boczku", "chudego boczku"));
        skladniki.put("salami", Arrays.asList("salami", "salami w plasterkach"));
        skladniki.put("ogórek", Arrays.asList("ogórek", "ogórki", "ogórków", "małych ogórków marynowanych", "świeży ogórek", "ogórki kiszone", "ogórków kiszonych", "duży obrany ogórek", "kwaszone ogórki", "duży ogórek", "średni ogórek wężowy", "ogórki kiszone", "soku z ogórków kiszonych", "ogórki konserwowe", "ogórek konserwowy"));
        skladniki.put("orzechy", Arrays.asList("orzechy", "orzechów", "posiekanych orzechów", "posiekanych orzechów włoskich", "orzechów laskowych", "orzeszki", "orzeszków", "pistacje", "pistacjowych"));
        skladniki.put("chrzan", Arrays.asList("chrzan", "chrzanu", "tartego chrzanu", "średniej wielkości korzenie chrzanu", "świeżo utartego chrzanu", "duży korzeń chrzanu", "utartego chrzanu", "odrobina chrzanu"));
        skladniki.put("jogut", Arrays.asList("jogurt", "jogurtu", "jogurt naturalny", "jogurtu naturalnego", "naturalnego jogurtu"));
        skladniki.put("łosoś", Arrays.asList("łosoś", "łososia", "wędzonego łososia"));
        skladniki.put("seler", Arrays.asList("seler", "selera", "seler naciowy", "selera naciowego", "młodego selera", "korzenia selera"));
        skladniki.put("awokado", Arrays.asList("awokado", "dojrzałych awokado"));
        skladniki.put("tabasco", Arrays.asList("tabasco", "sos tabasco", "sosu tabasco", "kilka kropek sosu tabasco"));
        skladniki.put("migdały", Arrays.asList("migdały", "płatki migdałów", "migdałów", "uprażonych płatków migdałów", "drobno posiekanych migdałów", "płatków migdałów"));
        skladniki.put("ryż", Arrays.asList("ryż", "ryżu", "ryż biały", "ryżu białego"));
        skladniki.put("grzyby", Arrays.asList("grzyby", "grzybów", "grzyby suszone", "suszone grzyby", "grzybów suszonych", "suszonych grzybów", "suszone lub świeże grzyby", "suszony grzybel", "suszonych prawdziwków", "grzybów shitake pokrojonych w plastry", "mrożonych prawdziwków", "podgrzybków", "grzybki boczniaki", "boczniaki", "boczniaków", "grzybów leśnych", "prawdziwków", "kurki", "kurek", "grzybów suszonych", "posiekanych, majerowanych grzybków", "smardze", "smardzów", "mun"));
        skladniki.put("ketchup", Arrays.asList("ketchup", "ketchupu", "keczupu", "keczup"));
        skladniki.put("woda", Arrays.asList("woda", "wody", "woda mineralna", "wody mineralnej", "wody mineralnej niegazowanej"));
        skladniki.put("zakwas", Arrays.asList("zakwas", "zakwasu", "zakwasu białego barszczu", "zakwasu barszczu białego", "zakwasu na żur"));
        skladniki.put("rosół", Arrays.asList("rosół", "rosołu", "rosołu mięsnego", "rosołu instant", "rosołu z kostki"));
        skladniki.put("burak", Arrays.asList("burak", "buraki", "buraków", "buraczki", "buraczków", "młodych buraczków", "średniej wielkości buraki", "nieduży burak"));
        skladniki.put("jabłko", Arrays.asList("jabłko", "jabłka", "soku jabłkowego", "duże jabłka", "jabłek"));
        skladniki.put("por", Arrays.asList("por", "pora", "poru", "zielone liście pora", "liście pora", "nieduży por", "mały por", "pory", "białej części pora"));
        skladniki.put("tymianek", Arrays.asList("tymianek", "tymianku", "świeżego tymianku"));
        skladniki.put("liść laurowy", Arrays.asList("liść laurowy", "liścia laurowego", "liście laurowe"));
        skladniki.put("czosnek", Arrays.asList("czosnek", "czosnku"));
        skladniki.put("cukier", Arrays.asList("cukier", "cukru", "cukru trzcinowego", "cukier puder", "cukru pudru"));
        skladniki.put("majeranek", Arrays.asList("majeranek", "majeranku", "otartego majeranku", "posiekanego majeranku"));
        skladniki.put("pieprz", Arrays.asList("pieprz", "pieprzu", "czarny pieprz", "czarny pieprz (w ziarenkach)", "świeżo mielony pieprz", "biały pieprz", "świeżo zmielony czarny pieprz", "pieprz mielony", "zmielony czarny pieprz", "pieprz ziarnisty", "ziaren czarnego pieprzu", "marynowanego pieprzu", "pieprz czarny mielony", "świeżo zmielony pieprz", "pieprz Cayenne"));
        skladniki.put("ocet", Arrays.asList("ocet", "octu", "ocet winny czerwony", "octu winnego", "ocet do smaku", "octu z marynaty grzybowej", "octu ryżowego"));
        skladniki.put("marchew", Arrays.asList("marchew", "marchwi", "młodej marchwi", "marcheka", "marchewki", "nieduże marchewki"));
        skladniki.put("wołowina", Arrays.asList("wołowina", "wołowina bez kości", "wołowiny bez kości", "wywar wołowy", "wywaru wołowego", "mielonej wołowiny", "mielona wołowina", "wołowiny", "mięsa wołowego bez kości", "mielonego mięsa wołowego" ));
        skladniki.put("mąka", Arrays.asList("mąka", "mąki", "mąki pszennej", "mąki ziemniaczanej", "mąka żytnia", "mąki żytniej", "mąki kukurydzianej", "mączka", "mączki"));
        skladniki.put("włoszczyzna", Arrays.asList("włoszczyzna", "włoszczyzny", "włoszczyzny z włoską kapustą", "włoszczyzny bez kapusty"));
        skladniki.put("fasola", Arrays.asList("fasola", "fasoli", "drobna fasoli", "drobnej fasoli", "fasola jaś", "fasoli jaś", "biała fasola", "białej fasoli", "suchej fasoli", "białej lub czerwonej suchej fasoli", "fasoli szparagowej", "czerwonej fasoli", "fasoli azuki", "fasoli z puszki", "fasolka szparagowa", "fasolka szparagowa (świeża lub mielona)", "fasolki"));
        skladniki.put("ziemniak", Arrays.asList("ziemniak", "ziemniaki", "ziemniaków", "mączyste ziemniaki"));
        skladniki.put("koperek", Arrays.asList("koperek", "koperku", "posiekanego koperku", "suszonego koperku", "kopru włoskiego"));
        skladniki.put("wieprzowina", Arrays.asList("wieprzowina", "wieprzowiny", "kości wieprzowych", "wieprzowe podgardle", "wątroby wieprzowej", "polędwicy wieprzowej", "szynki wieprzowej", "sznycle wieprzowe", "sznycle wieprzowe (po 10-12 dkg każdy)"));
        skladniki.put("cielęcina", Arrays.asList("cielęcina", "cielęciny", "tyleż cielęciny", "cielęciny zadniej bez kości", "cielęciny z udźca"));
        skladniki.put("kurczak", Arrays.asList("kurczak", "kurczaka", "grzbietów z kurczaka", "mięso z kurczaka", "mięsa z kurczaka", "drobno posiekanego mięsa z kurczaka"));
        skladniki.put("imbir", Arrays.asList("imbir", "imbiru", "zmielonego świeżego imbiru", "centymetr drobno posiekanego imbiru"));
        skladniki.put("kiełbasa", Arrays.asList("kiełbasa", "kiełbasy"));
        skladniki.put("wędzonka", Arrays.asList("wędzonka", "wędzonki", "wędzonki góralskiej"));
        skladniki.put("warzywa", Arrays.asList("warzywa", "warzyw", "wywar z warzyw", "wywaru z warzyw", "wywaru z warzyw lub z kostki warzywnej", "wywaru warzywnego"));
        skladniki.put("kostka warzywna", Arrays.asList("kostka warzywna", "kostki warzywnej", "wywar z kostki warzywnej", "wywaru z warzyw lub z kostki warzywnej"));
        skladniki.put("kminek", Arrays.asList("kminek", "kminku", "zmielonego kminku", "kminku arabskiego", "kminu rzymskiego", "mielonego kminkuu"));
        skladniki.put("zioła", Arrays.asList("zioła", "ziół", "zioła do dekoracji", "posiekanych ziół", "dowolne zioła"));
        skladniki.put("kapusta", Arrays.asList("kapusta", "kapusty", "kiszona kapusta", "kiszonej kapusty", "sok z kiszonej kapusty", "soku z kiszonej kapusty", "czerwona kapusta", "czerwonej kapusty", "małej główki czerwonej kapusty", "włoskiej kapusty"));
        skladniki.put("smalec", Arrays.asList("smalec", "smalcu"));
        skladniki.put("ziele angielskie", Arrays.asList("ziele angielskie", "ziela angielskiego", "ziarenka ziela angielskiego", "ziaren ziela angielskiego"));
        skladniki.put("schab", Arrays.asList("schab", "schabu"));
        skladniki.put("wino", Arrays.asList("wino", "wina", "czerwonego wytrawnego wina", "czerwonego, wytrawnego wina", "czerwonego wina", "białego wina wytrawnego lub półwytrawnego", "czerwone wino", "białego, wytrawnego wina", "białego wytrawnego wina", "słodkiego czerwonego wina"));
        skladniki.put("sos sojowy", Arrays.asList("sos sojowy", "sosu sojowego"));
        skladniki.put("vegeta", Arrays.asList("vegeta", "vegety", "przyprawa typu vegeta", "przyprawy typu vegeta"));
        skladniki.put("bulion", Arrays.asList("bulion", "bulionu", "bulion drobiowy", "bulionu drobiowego", "kostki bulionowe", "kostka rosołowa", "przyprawy do zup lub kostka rosołowa", "wywaru mięsnego", "bulionu warzywego", "bulionu jarzynowego", "wywaru", "wywar mięsny", "bulionu warzywnego instant", "bulionu z indyka w proszku", "bulion z indyka", "bulionu drobowio-warzywnego", "kostki rosołowe", "wywar drobiowy", "mocnego bulionu"));
        skladniki.put("chleb", Arrays.asList("chleb", "chleba", "biały chleb", "białego chleba", "chleba razowego bez skórki", "chleba tostowego", "suszonego chleba", "suszonego chlepa pszennego", "suszonego chleba razowego", "razowego chleba"));
        skladniki.put("brokuł", Arrays.asList("brokuł", "brokuły", "brokułów", "różyczki brokułu", "różyczek brokułu"));
        skladniki.put("słonina", Arrays.asList("słonina", "słoniny"));
        skladniki.put("makaron", Arrays.asList("makaron", "makaronu", "makaronu o dużych kształtach", "drobnego makaronu", "makaronu nitki", "spaghetti", "tortellini", "makaronu ryżowego"));
        skladniki.put("przyprawa", Arrays.asList("przyprawa", "przyprawy", "przyprawa warzywna", "przyprawa do zupe"));
        skladniki.put("dynia", Arrays.asList("dynia", "dyni", "świeżej dyni"));
        skladniki.put("gałka muszkatołowa", Arrays.asList("gałka muszkatołowa", "gałki muszkatołowej", "mielonej gałki muszkatołowej"));
        skladniki.put("curry", Arrays.asList("curry", "proszku curry"));
        skladniki.put("cukinia", Arrays.asList("cukinia", "cukini", "młodych owoców cukini"));
        skladniki.put("mięso", Arrays.asList("mięso", "mięsa", "łopatka lub żeberka, mogąbyć wędzone", "mięso tłuste", "wędzonka", "wędzonki", "mięso mielone", "mięso mielone wieprzowe, wołowe lub wieprzowo-wołowe", "mielonego mięsa", "polędwicy", "skrzydełek drobiowych", "plastry wątróbki po 100 g", "dowolne mięso", "karczku", "łopatki", "wątróbki"));
        skladniki.put("maggi", Arrays.asList("maggi"));
        skladniki.put("baranina", Arrays.asList("baranina", "baraniny"));
        skladniki.put("karkówka", Arrays.asList("karkówka", "karkówki"));
        skladniki.put("truskawka", Arrays.asList("truskawka", "truskawki", "truskawek"));
        skladniki.put("maślanka", Arrays.asList("maślanka", "maślanki"));
        skladniki.put("beza", Arrays.asList("beza", "bezy", "małe bezy do dekoracji"));
        skladniki.put("żeberka", Arrays.asList("żeberka", "żeberek", "łopatka lub żeberka"));
        skladniki.put("olej", Arrays.asList("olej", "oleju"));
        skladniki.put("mintaj", Arrays.asList("mintaj", "mintaja", "filety z mintaja", "filetów z mintaja"));
        skladniki.put("naleśnik", Arrays.asList("naleśnik", "naleśniki"));
        skladniki.put("sandacz", Arrays.asList("sandacz", "sandacza"));
        skladniki.put("szczupak", Arrays.asList("szczupak", "szczupaka"));
        skladniki.put("chili", Arrays.asList("chili", "czerwonej, posiekanej papryczki chili", "posiekanej papryczki chili", "papryka chili", "czerwone papryczki chili"));
        skladniki.put("trawa cytrynowa", Arrays.asList("trawa cytrynowa", "trawy cytrynowej"));
        skladniki.put("kolendra", Arrays.asList("kolendra", "kolendry"));
        skladniki.put("ryba", Arrays.asList("ryba", "ryby", "ryby morskiej", "dorady", "dorsz", "dorsza", "halibut", "halibuta", "śledzie", "sardele", "sardeli", "wywaru z ryby", "karp", "karpie", "karpia", "okonie", "pstrągi", "pstrągów", "sandacza", "sandacz", "miecznika", "suma", "tuńczyka", "filetów śledziowych", "śledziowe", "filecików helskich"));
        skladniki.put("limonka", Arrays.asList("limonka", "limonki", "sok z limonki", "soku z limonki", "limetki", "limetka"));
        skladniki.put("sos", Arrays.asList("sos", "sosu", "sosu rybnego"));
        skladniki.put("kefir", Arrays.asList("kefir", "kefiru"));
        skladniki.put("szczaw", Arrays.asList("szczaw", "szczawiu", "świeżego szczawiu"));
        skladniki.put("liść bobkowy", Arrays.asList("liść bobkowy"));
        skladniki.put("tłuszcz", Arrays.asList("tłuszcz", "tłuszczu"));
        skladniki.put("czekolada", Arrays.asList("czekolada", "czekolady"));
        skladniki.put("kalafior", Arrays.asList("kalafior", "kalafioru", "mały fioletowy kalafior", "kalafiora"));
        skladniki.put("indyk", Arrays.asList("indyk", "indyka", "udźca z indyka", "piersi z indyka", "filetów z piersi indyka", "piersi indyka"));
        skladniki.put("kasztany", Arrays.asList("kasztany", "kasztanów", "konserwowych kasztanów"));
        skladniki.put("brukselka", Arrays.asList("brukselka", "brukselki"));
        skladniki.put("szałwia", Arrays.asList("szałwia", "szałwi", "świeżej szałwi", "świeżej szałwi lub bazylii"));
        skladniki.put("bazylia", Arrays.asList("bazylia", "bazylii", "świeżej szałwi lub bazylii"));
        skladniki.put("piwo", Arrays.asList("piwo", "piwa", "jasnego piwa"));
        skladniki.put("ser biały", Arrays.asList("ser biały", "sera białego"));
        skladniki.put("goździki", Arrays.asList("goździki", "goździków"));
        skladniki.put("cynamon", Arrays.asList("cynamon", "cynamonu"));
        skladniki.put("szpinak", Arrays.asList("szpinak", "szpinaku"));
        skladniki.put("śliwka", Arrays.asList("śliwka", "śliwki", "śliwek", "suszone śliwki", "suszonych śliwek"));
        skladniki.put("rodzynki", Arrays.asList("rodzynki", "rodzynek", "rodzynków"));
        skladniki.put("cykoria", Arrays.asList("cykoria", "cykorii"));
        skladniki.put("melon", Arrays.asList("melon", "melony", "zielony melon"));
        skladniki.put("miód", Arrays.asList("miód", "miodu", "miodu akacjowego"));
        skladniki.put("mięta", Arrays.asList("mięta", "mięty"));
        skladniki.put("gorczyca", Arrays.asList("gorczyca", "gorczycy"));
        skladniki.put("soczewica", Arrays.asList("soczewica", "soczewicy", "czerwonej soczewicy"));
        skladniki.put("szparagi", Arrays.asList("szparagi", "szparagów", "białych szparagów", "świeżych jasnych szparagów"));
        skladniki.put("oregano", Arrays.asList("oregano"));
        skladniki.put("brzoskwinia", Arrays.asList("brzoswkinia", "brzoskwinie", "brzoskiwń", "połówki brzoskwiń z kompotu"));
        skladniki.put("wiśnie", Arrays.asList("wiśnie", "sok wiśniowy", "soku wiśniowego"));
        skladniki.put("porzeczka", Arrays.asList("porzeczka", "porzeczki", "czerwona porzeczka", "czerwonej porzeczki", "soku z czerwonych porzeczek", "porzeczek"));
        skladniki.put("szafran", Arrays.asList("szafran", "szafranu", "nitek szafranu"));
        skladniki.put("centymetr", Arrays.asList("centymetr", "cm", "centymetrów", "centymetra"));
        skladniki.put("winogrona", Arrays.asList("winogrona", "winogron", "wydrylowanych, rozdrobnionych białych winogron"));
        skladniki.put("camembert", Arrays.asList("camembert", "serka camemvert, obranego ze skórki"));
        skladniki.put("topinambur", Arrays.asList("topinambur", "topinambura"));
        skladniki.put("ananas", Arrays.asList("ananas", "ananasa", "krążki ananasa z puszki", "ananasa z puszki"));
        skladniki.put("morele", Arrays.asList("morele", "moreli", "moreli z puszki"));
        skladniki.put("chutney", Arrays.asList("chutney", "chutneya", "ostrego chutneya owocowego"));
        skladniki.put("kalarepa", Arrays.asList("kalarepa", "duża kalarepka"));
        skladniki.put("kaczka", Arrays.asList("kaczka", "kaczki", "młoda kaczka" ));
        skladniki.put("twaróg", Arrays.asList("twaróg", "twarogu", "twarożku", "twarożek"));
        skladniki.put("banan", Arrays.asList("banan", "banany"));
        skladniki.put("kaszanka", Arrays.asList("kaszanka", "kaszanki"));
        skladniki.put("oscypek", Arrays.asList("oscypek", "oscypka"));
        skladniki.put("sezam", Arrays.asList("sezam", "sezamu"));
        skladniki.put("gruszka", Arrays.asList("gruszka", "gruszek", "gruszki"));
        skladniki.put("mozzarella", Arrays.asList("mozarella", "mozzarelli"));
        skladniki.put("kotlety", Arrays.asList("kotlety", "kotletów"));
        skladniki.put("jagnęcina", Arrays.asList("jagnęcina", "jagnęciny"));
        skladniki.put("rozmaryn", Arrays.asList("rozmaryn"));
        skladniki.put("owoce", Arrays.asList("owoce", "owoców", "owocowego"));
        skladniki.put("żelatyna", Arrays.asList("żelatyna", "żelatyny"));
        skladniki.put("kolby", Arrays.asList("kolby", "kolb"));
        skladniki.put("rabarbar", Arrays.asList("rabarbar", "rabarbaru"));
        skladniki.put("cząber", Arrays.asList("cząber"));
        skladniki.put("bakłażan", Arrays.asList("bakłażan", "bakłażany", "bakłażanów"));
        skladniki.put("pestki", Arrays.asList("pestki", "pestek"));
        skladniki.put("zielenina", Arrays.asList("zielenina"));
        skladniki.put("borówki", Arrays.asList("borówki", "borówek"));
        skladniki.put("żurawina", Arrays.asList("żurawina", "żurawiny"));
        skladniki.put("estragon", Arrays.asList("estragon", "estragonu"));
        skladniki.put("ciasto francuskie", Arrays.asList("ciasto francuskie", "ciasta francuskiego"));
        skladniki.put("ser", Arrays.asList("ser", "sera", "serek", "serka", "ricotta", "ricotty", "ementaler", "ementalera", "bryndzy", "gruyere", "solan", "feta", "fety", "hermeliny"));
        skladniki.put("cannelloni", Arrays.asList("cannelloni"));
        skladniki.put("bekon", Arrays.asList("bekon", "bekonu"));
        skladniki.put("kasza", Arrays.asList("kasza", "kaszy"));
        skladniki.put("margaryna", Arrays.asList("margaryna", "margaryny"));
        skladniki.put("korzeń", Arrays.asList("korzeń", "korzenie"));
        skladniki.put("anchios", Arrays.asList("anchios"));
        skladniki.put("filet", Arrays.asList("filet", "filetu", "filety", "filetów"));
        skladniki.put("opieniek", Arrays.asList("opieniek"));
        skladniki.put("małże", Arrays.asList("małże", "małży"));
        skladniki.put("mortadela", Arrays.asList("mortadela", "mortadeli"));
        skladniki.put("dressing", Arrays.asList("dressing", "dressingu"));
        skladniki.put("bakalie", Arrays.asList("bakalie", "bakalii"));
        skladniki.put("tuńczyk", Arrays.asList("tuńczyk", "tuńczyka"));
        skladniki.put("paczka", Arrays.asList("paczka", "paczki"));
        skladniki.put("likier", Arrays.asList("likier", "likieru"));
        skladniki.put("kalmary", Arrays.asList("kalmary", "kalmarów"));
        skladniki.put("kapary", Arrays.asList("kapary", "kaparów"));
        skladniki.put("jałowiec", Arrays.asList("jałowiec", "jałowca"));
        skladniki.put("ślimaki", Arrays.asList("ślimaki", "ślimaków"));
        skladniki.put("drożdże", Arrays.asList("drożdże", "drożdży"));
        skladniki.put("rzeżucha", Arrays.asList("rzeżucha", "rzeżuchy"));
        skladniki.put("kiwi", Arrays.asList("kiwi"));
        skladniki.put("mango", Arrays.asList("mango"));
        skladniki.put("melisa", Arrays.asList("melisa", "melisy"));
        skladniki.put("czereśnie", Arrays.asList("czereśnie", "czereśni"));
        skladniki.put("agrest", Arrays.asList("agrest", "agrestu"));
        skladniki.put("szynka", Arrays.asList("szynka", "szynki"));
        skladniki.put("płat", Arrays.asList("płat", "płaty"));
        skladniki.put("winegret", Arrays.asList("winegret"));
        skladniki.put("granat", Arrays.asList("granat", "granaty", "granatu", "granatów"));
        skladniki.put("kompot", Arrays.asList("kompot", "kompotu"));
        skladniki.put("rukola", Arrays.asList("rukola", "rukoli"));
        skladniki.put("mandarynka", Arrays.asList("mandarynka", "mandarynek", "mandarynki"));
        skladniki.put("kwiat akacji", Arrays.asList("kwiat akacji"));
        skladniki.put("ciasto", Arrays.asList("ciasto", "ciasta"));
        skladniki.put("porcja", Arrays.asList("porcja", "porcje", "porcji"));
        skladniki.put("kurkuma", Arrays.asList("kurkuma", "kurkumy"));
        skladniki.put("aromat", Arrays.asList("aromat", "aromatu"));
        skladniki.put("sok", Arrays.asList("sok", "soku"));
        skladniki.put("figa", Arrays.asList("figa", "figi", "fig"));
        skladniki.put("arbuz", Arrays.asList("arbuz", "arbuzy", "arbuza"));
        skladniki.put("cydr", Arrays.asList("cydr", "cydru"));
        skladniki.put("maliny", Arrays.asList("maliny", "malin", "malinowy", "malinowego"));
        skladniki.put("anyż", Arrays.asList("anyż", "anyżu", "anyżku"));
        skladniki.put("biszkopt", Arrays.asList("biszkopt", "biszkopty", "biszkoptów", "blat biszkoptowy"));
        skladniki.put("budyń", Arrays.asList("budyń", "budyniu", "budynie"));
        skladniki.put("jagody", Arrays.asList("jagody", "jagód"));
        skladniki.put("konfitura", Arrays.asList("konfitura", "konfitury", "konfitur"));
        skladniki.put("herbatniki", Arrays.asList("herbatniki", "herbatników"));
        skladniki.put("nektarynki", Arrays.asList("nektarynki", "nektarynek"));
        skladniki.put("posypka", Arrays.asList("posypka", "posypki"));
        skladniki.put("galaretka", Arrays.asList("galaretka", "galaretki", "galaretek"));
        skladniki.put("rum", Arrays.asList("rum", "rumu"));
        skladniki.put("proszek", Arrays.asList("proszek", "proszku"));
        skladniki.put("draże", Arrays.asList("draże", "draży"));
        skladniki.put("barwnik", Arrays.asList("barwnik", "barwniki", "barwników"));
        skladniki.put("pszenica", Arrays.asList("pszenica", "pszenicy"));
        skladniki.put("mak", Arrays.asList("mak", "maku"));
        skladniki.put("kawa", Arrays.asList("kawa", "kawy"));
        skladniki.put("wiórki", Arrays.asList("wiórki", "wiórek", "wiórków"));
        skladniki.put("lody", Arrays.asList("lody", "lodów"));
        skladniki.put("esencja", Arrays.asList("esencja", "esencji"));
        skladniki.put("daktyle", Arrays.asList("daktyle", "daktyli"));
        skladniki.put("wanilia", Arrays.asList("wanilia", "wanilii"));
        skladniki.put("tabliczka", Arrays.asList("tabliczka", "tabliczki", "tabliczek"));
        skladniki.put("herbata", Arrays.asList("herbata", "herbaty"));
        skladniki.put("soda", Arrays.asList("soda", "sody"));
        skladniki.put("wafle", Arrays.asList("wafle", "wafli"));
        skladniki.put("kardamon", Arrays.asList("kardamon", "kardamonu"));
        skladniki.put("spirytus", Arrays.asList("spirytus", "spirytusu"));
        skladniki.put("kakao", Arrays.asList("kakao"));
        skladniki.put("Śnieżka", Arrays.asList("Śnieżka", "Śnieżki"));
        skladniki.put("ajerkoniak", Arrays.asList("ajerkoniak", "ajerkoniaku"));
        skladniki.put("wódka", Arrays.asList("wódka", "wódki"));
        skladniki.put("powidła", Arrays.asList("powidła", "powideł"));
        skladniki.put("amaretto", Arrays.asList("amaretto"));
        skladniki.put("manny", Arrays.asList("manny", "manna"));
        skladniki.put("gin", Arrays.asList("gin", "ginu"));
        skladniki.put("wermut", Arrays.asList("wermut", "wermutu"));
        skladniki.put("lód", Arrays.asList("lód", "lodu"));
        skladniki.put("pasek", Arrays.asList("pasek", "paska", "pasku", "paski", "paseczek", "paseczki", "paseczków"));
        skladniki.put("karambola", Arrays.asList("karambola"));
        skladniki.put("szampan", Arrays.asList("szampan", "szampana"));
        skladniki.put("kiwat", Arrays.asList("kwiat", "kwiatu", "kwiaty", "kwiatów"));
        skladniki.put("kora", Arrays.asList("kora", "kory"));
        skladniki.put("gałka", Arrays.asList("gałka", "gałki", "gałek"));
        skladniki.put("jarzębina", Arrays.asList("jarzębina", "jarzębiny"));
        skladniki.put("gąsek", Arrays.asList("gąsek"));
        skladniki.put("nasiona", Arrays.asList("nasiona", "nasion", "nasionka", "nasionek"));

        return skladniki;
    }

    public static String znajdzNazweSkladnika(String skladnik) {
        for (Entry<String, List<String>> entry : getSkladnikiMap().entrySet()) {
            for (String forma : entry.getValue()) {
                if (skladnik.contains(forma)) {
                    return entry.getKey();
                }
            }
        }
        return "Nie znaleziono"; // lub inna wartość domyślna
    }



}
